### ISSUE TITLE
pullQueue.shift error?

### ISSUE THREAD

**Issue by awwong1** [udia-software/graphql-postgres-subscriptions#3]
Using `1.0.1`, saw this appear all of a sudden?

```text
(node:68550) UnhandledPromiseRejectionWarning: TypeError: this.pullQueue.shift(...) is not a function
    at PubSubAsyncIterator.<anonymous> (/Users/alexander/sandbox/src/pi.alexander-wong.com/udia-software/udia/node_modules/@udia/graphql-postgres-subscriptions/dist/PubSubAsyncIterator.js:47:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alexander/sandbox/src/pi.alexander-wong.com/udia-software/udia/node_modules/@udia/graphql-postgres-subscriptions/dist/PubSubAsyncIterator.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:68550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by awwong1** [comment]
I don't see anywhere this can be set to anything other than an array, which should have the `shift` function.

```js
export default class PubSubAsyncIterator<T> implements AsyncIterator<any> {
  private pullQueue: Array<(data: any) => void>; // array of empty promises
  // ...
  constructor(pubsub: PubSubEngine, eventNames: string | string[]) {
    this.pullQueue = []; // set to array in constructor
  }
  // ...
  private async pushValue(event: any) {
    await this.allSubscribed;
    if (this.pullQueue.length > 0) {
      this.pullQueue.shift()!({ value: event, done: false }); // error was thrown here?
    } else {
      this.pullQueue.push(event);
    }
  }

  private pullValue(): Promise<IteratorResult<any>> {
    return new Promise(resolve => {
      if (this.pushQueue.length !== 0) {
        resolve({ value: this.pushQueue.shift(), done: false });
      } else {
        this.pullQueue.push(resolve); // add to array
      }
    });
  }

  private emptyQueue(subscriptionIds: number[]) {
    if (this.listening) {
      this.listening = false;
      this.unsubscribeAll(subscriptionIds);
      this.pullQueue.forEach(resolve => // dump the items in the pullQueue and empty?
        resolve({ value: undefined, done: true })
      );
      this.pullQueue.length = 0;
      this.pushQueue.length = 0;
    }
  }
  // ...
}


```

**Comment by awwong1** [comment]
https://github.com/udia-software/graphql-postgres-subscriptions/commit/d34bb973d3e3d02f0b39d9bb3e301fe1a28da06a
